USE CourseDB;
SET foreign_key_checks=0;
LOAD DATA LOCAL INFILE 'course.csv' INTO TABLE course 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';


LOAD DATA LOCAL INFILE 'elective.csv' INTO TABLE elective 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';

LOAD DATA LOCAL INFILE 'majors.csv' INTO TABLE major 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';

LOAD DATA LOCAL INFILE 'preReq.csv' INTO TABLE prerequisite 
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';

LOAD DATA LOCAL INFILE 'requirment .csv' INTO TABLE requirment
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r';
SET foreign_key_checks=1;